import { Component } from 'react';
import './Portfolio.css';
import plants_pic from './plants.jpg';
import lttb_pic from './lttb.png';
import llm_pic from './llm.webp';

class Portfolio extends Component {
  constructor(props) {
    super(props);
    this.state = {
      projects: [
        {
          project_image: lttb_pic,
          title: "Down Sampling Algorithm for Data Visualization Optimization",
          description:
            "A Python algorithm for filtering time series data to be loaded onto an online data visualization toolkit to reduce data load while maintaining shape.",
          technologies: ["Python", "Statistics", "Plotly", "Dash"],
        },
        {
          project_image: plants_pic,
          title: "Plant Specimen Image Classification for NYBG",
          description:
            "Developed a machine learning pipeline to preprocess and classify image data, leveraging a Keras Sequential Model for image classification.",
          technologies: ["Python", "Pandas", "Keras", "PostgreSQL"],
        },
        {
          project_image: llm_pic,
          title: "Context Engineering for Text-to-SQL LLM",
          description:
            "Performed context engineering to improve the accuracy of SQL statements generated by an LLM from a natural language question.",
          technologies: ["SQL", "Snowflake", "LLM", "Context Engineering"],
        },
      ],
    };
  }

  render() {
    return (
      <div className="portfolio-section">
        <h1 className="portfolio-title">My Portfolio</h1>
        <div className="portfolio-grid">
          {this.state.projects.map((project, index) => (
            <div key={index} className="project-card">
              <div className="project-image">
                <img src={project.project_image} alt={project.title} />
              </div>
              <div className="project-content">
                <h2 className="project-title">{project.title}</h2>
                <p className="project-description">{project.description}</p>
                <div className="technology-tags">
                  {project.technologies.map((tech, i) => (
                    <span key={i} className="technology-tag">
                      {tech}
                    </span>
                  ))}
                </div>
                <div className="project-buttons">
                  <button className="demo-button">Live Demo</button>
                  <button className="docs-button">View Documentation</button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }
}

export default Portfolio;
